//! Age Verification Smart Contract for Arbitrum Stylus
//! 
//! This contract verifies ZK proofs generated by the SP1 proof server
//! and stores validation results onchain.
//!
//! Note: SP1 verifier is a Solidity contract, so we call it as an external contract.

#![no_std]

#[macro_use]
extern crate alloc;

use alloc::vec::Vec;
use stylus_sdk::{
    alloy_primitives::{Address, Bytes, FixedBytes, U256},
    alloy_sol_types::sol,
    msg, prelude::*,
    storage::{StorageAddress, StorageBytes32, StorageBool, StorageU256},
    evm,
};

// Define Solidity-compatible types
sol! {
    struct ProofRecord {
        address user;
        bytes32 documentNumberHash;
        bool isValid;
        bool meetsAgeRequirement;
        uint256 timestamp;
        bool exists;
    }

    error DocumentNumberAlreadyUsed();
    error InvalidProof();
    error ProofRecordNotFound();
}

// SP1 Verifier contract interface (Solidity contract we'll call)
sol! {
    interface SP1Verifier {
        function verify(bytes32 vkey, bytes calldata proof, bytes calldata publicValues) external view returns (bool);
    }
}

// Storage layout
const PROOF_RECORDS_SLOT: u64 = 0;
const USER_PROOFS_SLOT: u64 = 1;
const VKEY_SLOT: u64 = 2;
const VERIFIER_ADDRESS_SLOT: u64 = 3;

/// Storage for proof records: documentNumberHash => ProofRecord
struct ProofRecordStorage {
    user: StorageAddress,
    document_number_hash: StorageBytes32,
    is_valid: StorageBool,
    meets_age_requirement: StorageBool,
    timestamp: StorageU256,
    exists: StorageBool,
}

impl ProofRecordStorage {
    fn new(document_number_hash: FixedBytes<32>) -> Self {
        let base_slot = Self::slot_for(document_number_hash);
        Self {
            user: StorageAddress::new(base_slot),
            document_number_hash: StorageBytes32::new(base_slot + 1),
            is_valid: StorageBool::new(base_slot + 2),
            meets_age_requirement: StorageBool::new(base_slot + 3),
            timestamp: StorageU256::new(base_slot + 4),
            exists: StorageBool::new(base_slot + 5),
        }
    }

    fn slot_for(document_number_hash: FixedBytes<32>) -> u64 {
        // Hash documentNumberHash with slot to get unique storage location
        let mut input = Vec::new();
        input.extend_from_slice(document_number_hash.as_slice());
        input.extend_from_slice(&PROOF_RECORDS_SLOT.to_be_bytes());
        let hash = stylus_sdk::crypto::keccak256(&input);
        // Use first 8 bytes as slot (simplified - in production use proper slot calculation)
        u64::from_be_bytes([
            hash[0], hash[1], hash[2], hash[3],
            hash[4], hash[5], hash[6], hash[7],
        ])
    }

    fn get(&self) -> Option<ProofRecord> {
        if !self.exists.get() {
            return None;
        }
        Some(ProofRecord {
            user: self.user.get(),
            documentNumberHash: self.document_number_hash.get(),
            isValid: self.is_valid.get(),
            meetsAgeRequirement: self.meets_age_requirement.get(),
            timestamp: self.timestamp.get(),
            exists: true,
        })
    }

    fn set(&self, record: &ProofRecord) {
        self.user.set(record.user);
        self.document_number_hash.set(record.documentNumberHash);
        self.is_valid.set(record.isValid);
        self.meets_age_requirement.set(record.meetsAgeRequirement);
        self.timestamp.set(record.timestamp);
        self.exists.set(true);
    }
}

/// Storage for user proofs count and hashes
struct UserProofsStorage {
    user: Address,
    count: StorageU256,
}

impl UserProofsStorage {
    fn new(user: Address) -> Self {
        let base_slot = Self::slot_for(user);
        Self {
            user,
            count: StorageU256::new(base_slot),
        }
    }

    fn slot_for(user: Address) -> u64 {
        let mut input = Vec::new();
        input.extend_from_slice(user.as_slice());
        input.extend_from_slice(&USER_PROOFS_SLOT.to_be_bytes());
        let hash = stylus_sdk::crypto::keccak256(&input);
        u64::from_be_bytes([
            hash[0], hash[1], hash[2], hash[3],
            hash[4], hash[5], hash[6], hash[7],
        ])
    }

    fn push(&self, document_number_hash: FixedBytes<32>) {
        let count = self.count.get();
        // Store hash at index using mapping pattern: keccak256(user || slot || index)
        let hash_slot = Self::slot_for_hash(self.user, count);
        StorageBytes32::new(hash_slot).set(document_number_hash);
        self.count.set(count + U256::from(1));
    }

    fn slot_for_hash(user: Address, index: U256) -> u64 {
        let mut input = Vec::new();
        input.extend_from_slice(user.as_slice());
        input.extend_from_slice(&USER_PROOFS_SLOT.to_be_bytes());
        let mut index_bytes = [0u8; 32];
        index.to_be_bytes::<32>().copy_to_slice(&mut index_bytes);
        input.extend_from_slice(&index_bytes);
        let hash = stylus_sdk::crypto::keccak256(&input);
        u64::from_be_bytes([
            hash[0], hash[1], hash[2], hash[3],
            hash[4], hash[5], hash[6], hash[7],
        ])
    }

    fn get_count(&self) -> U256 {
        self.count.get()
    }

    fn get_at(&self, index: U256) -> FixedBytes<32> {
        let hash_slot = Self::slot_for_hash(self.user, index);
        StorageBytes32::new(hash_slot).get()
    }
}

// Main contract entrypoints

/// Verify age proof and store result
#[entrypoint]
pub fn verify_age_proof(
    proof: Bytes,
    public_values: Bytes,
    document_number_hash: FixedBytes<32>,
) -> Result<(bool, bool), Vec<u8>> {
    // Check if document number already used
    let record_storage = ProofRecordStorage::new(document_number_hash);
    if record_storage.exists.get() {
        return Err(DocumentNumberAlreadyUsed {}.encode());
    }

    // Get vkey and verifier address from storage
    let vkey = StorageBytes32::new(VKEY_SLOT).get();
    let verifier_address = StorageAddress::new(VERIFIER_ADDRESS_SLOT).get();
    
    if verifier_address == Address::ZERO {
        return Err(InvalidProof {}.encode());
    }

    // Call SP1 verifier contract (Solidity contract)
    // Use evm::call to call external Solidity contract
    let verifier_interface = SP1Verifier::new(verifier_address);
    let call_data = verifier_interface.verify(vkey, proof.clone(), public_values.clone());
    
    let result = evm::call(
        &evm::CallOpts {
            to: verifier_address,
            data: Some(call_data.abi_encode()),
            ..Default::default()
        },
    );
    
    let proof_valid = match result {
        Ok(output) => {
            // Decode bool return value
            if output.len() >= 32 {
                output[31] != 0 // Last byte of 32-byte word
            } else {
                false
            }
        }
        Err(_) => return Err(InvalidProof {}.encode()),
    };

    if !proof_valid {
        return Err(InvalidProof {}.encode());
    }

    // Decode public values to extract output
    let (is_valid, meets_age_requirement) = decode_public_values(&public_values)
        .map_err(|_| InvalidProof {}.encode())?;

    // Store proof record
    let record = ProofRecord {
        user: msg::sender(),
        documentNumberHash: document_number_hash,
        isValid: is_valid,
        meetsAgeRequirement: meets_age_requirement,
        timestamp: U256::from(msg::timestamp()),
        exists: true,
    };
    record_storage.set(&record);

    // Track for user
    let user_proofs = UserProofsStorage::new(msg::sender());
    user_proofs.push(document_number_hash);

    // Emit event via log
    stylus_sdk::log::info(&format!(
        "AgeProofVerified user={:?} docHash={:?} isValid={} meetsAge={}",
        msg::sender(),
        document_number_hash,
        is_valid,
        meets_age_requirement
    ));

    Ok((is_valid, meets_age_requirement))
}

/// Verify proof without storing (view function)
#[entrypoint]
pub fn verify_proof_only(proof: Bytes, public_values: Bytes) -> Result<bool, Vec<u8>> {
    let vkey = StorageBytes32::new(VKEY_SLOT).get();
    let verifier_address = StorageAddress::new(VERIFIER_ADDRESS_SLOT).get();
    
    if verifier_address == Address::ZERO {
        return Err(InvalidProof {}.encode());
    }

    let verifier_interface = SP1Verifier::new(verifier_address);
    let call_data = verifier_interface.verify(vkey, proof, public_values);
    
    let result = evm::call(
        &evm::CallOpts {
            to: verifier_address,
            data: Some(call_data.abi_encode()),
            ..Default::default()
        },
    );
    
    match result {
        Ok(output) => {
            Ok(if output.len() >= 32 {
                output[31] != 0
            } else {
                false
            })
        }
        Err(_) => Err(InvalidProof {}.encode()),
    }
}

/// Get proof record
#[entrypoint]
pub fn get_proof_record(document_number_hash: FixedBytes<32>) -> Result<ProofRecord, Vec<u8>> {
    let record_storage = ProofRecordStorage::new(document_number_hash);
    record_storage.get()
        .ok_or_else(|| ProofRecordNotFound {}.encode())
}

/// Check if document number is used
#[entrypoint]
pub fn is_document_number_used(document_number_hash: FixedBytes<32>) -> bool {
    let record_storage = ProofRecordStorage::new(document_number_hash);
    record_storage.exists.get()
}

/// Get user proofs count
#[entrypoint]
pub fn get_user_proofs_count(user: Address) -> U256 {
    let user_proofs = UserProofsStorage::new(user);
    user_proofs.get_count()
}

/// Get user proof at index
#[entrypoint]
pub fn get_user_proof_at(user: Address, index: U256) -> FixedBytes<32> {
    let user_proofs = UserProofsStorage::new(user);
    user_proofs.get_at(index)
}

/// Initialize contract (constructor equivalent)
#[entrypoint]
pub fn init(vkey: FixedBytes<32>, verifier_address: Address) {
    StorageBytes32::new(VKEY_SLOT).set(vkey);
    StorageAddress::new(VERIFIER_ADDRESS_SLOT).set(verifier_address);
}

// Helper functions

/// Decode public values to extract AgeProofOutput
/// Public values are bincode-serialized: [length, is_valid: bool, meets_age_requirement: bool, ...]
fn decode_public_values(public_values: &Bytes) -> Result<(bool, bool), ()> {
    if public_values.len() < 2 {
        return Err(());
    }
    
    // Skip length prefix (bincode varint, typically 1 byte)
    let offset = 1;
    
    if offset >= public_values.len() {
        return Err(());
    }
    
    // Read is_valid (bool, 1 byte)
    let is_valid = public_values[offset] != 0;
    
    if offset + 1 >= public_values.len() {
        return Err(());
    }
    
    // Read meets_age_requirement (bool, 1 byte)
    let meets_age_requirement = public_values[offset + 1] != 0;
    
    Ok((is_valid, meets_age_requirement))
}
