// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {SP1Verifier} from "@succinctlabs/sp1-sdk/contracts/SP1Verifier.sol";

/**
 * @title AgeVerification
 * @notice Smart contract for verifying passport age proofs using SP1 zkVM
 * @dev This contract verifies ZK proofs generated by the proof server and stores validation results
 */
contract AgeVerification {
    // SP1 Verifier contract
    SP1Verifier public immutable verifier;
    
    // Verification key (programVKey) - set at deployment
    bytes32 public immutable vkey;
    
    // Struct to store proof validation results
    struct ProofRecord {
        address user;                    // Address that submitted the proof
        bytes32 documentNumberHash;      // Hash of document number (for uniqueness)
        bool isValid;                    // Is passport valid?
        bool meetsAgeRequirement;        // Does person meet age requirement?
        uint256 timestamp;               // When proof was verified
        bool exists;                     // Does this record exist?
    }
    
    // Mapping: documentNumberHash => ProofRecord
    // Prevents replay attacks by tracking used document numbers
    mapping(bytes32 => ProofRecord) public proofRecords;
    
    // Mapping: user => array of documentNumberHashes they've verified
    mapping(address => bytes32[]) public userProofs;
    
    // Events
    event AgeProofVerified(
        address indexed user,
        bytes32 indexed documentNumberHash,
        bool isValid,
        bool meetsAgeRequirement,
        uint256 timestamp
    );
    
    event ProofRejected(
        address indexed user,
        bytes32 indexed documentNumberHash,
        string reason
    );
    
    /**
     * @notice Constructor - sets up verifier and vkey
     * @param _vkey The verification key (programVKey) from the proof server
     */
    constructor(bytes32 _vkey) {
        verifier = new SP1Verifier();
        vkey = _vkey;
    }
    
    /**
     * @notice Verify an age proof and store the result
     * @param proof The ZK proof bytes (from proof server)
     * @param publicValues The public values bytes (from proof server)
     * @param documentNumberHash The hash of the document number (from proof server output)
     * @return isValid Whether the passport is valid
     * @return meetsAgeRequirement Whether the person meets the age requirement
     */
    function verifyAgeProof(
        bytes calldata proof,
        bytes calldata publicValues,
        bytes32 documentNumberHash
    ) external returns (bool isValid, bool meetsAgeRequirement) {
        // Check if this document number has already been used (prevent replay attacks)
        if (proofRecords[documentNumberHash].exists) {
            emit ProofRejected(msg.sender, documentNumberHash, "Document number already used");
            revert("Document number already verified");
        }
        
        // Verify the ZK proof using SP1 verifier
        bool proofValid = verifier.verify(vkey, proof, publicValues);
        
        if (!proofValid) {
            emit ProofRejected(msg.sender, documentNumberHash, "Proof verification failed");
            revert("Invalid proof");
        }
        
        // Decode public values to extract output
        // Public values contain the AgeProofOutput struct serialized with bincode
        // We need to decode it to get is_valid and meets_age_requirement
        (isValid, meetsAgeRequirement) = decodePublicValues(publicValues);
        
        // Store the proof record
        proofRecords[documentNumberHash] = ProofRecord({
            user: msg.sender,
            documentNumberHash: documentNumberHash,
            isValid: isValid,
            meetsAgeRequirement: meetsAgeRequirement,
            timestamp: block.timestamp,
            exists: true
        });
        
        // Track this proof for the user
        userProofs[msg.sender].push(documentNumberHash);
        
        // Emit event
        emit AgeProofVerified(
            msg.sender,
            documentNumberHash,
            isValid,
            meetsAgeRequirement,
            block.timestamp
        );
    }
    
    /**
     * @notice Verify proof without storing (view function)
     * @param proof The ZK proof bytes
     * @param publicValues The public values bytes
     * @return isValid Whether the proof is valid
     */
    function verifyProofOnly(
        bytes calldata proof,
        bytes calldata publicValues
    ) external view returns (bool isValid) {
        return verifier.verify(vkey, proof, publicValues);
    }
    
    /**
     * @notice Get proof record for a document number hash
     * @param documentNumberHash The hash of the document number
     * @return record The proof record
     */
    function getProofRecord(bytes32 documentNumberHash)
        external
        view
        returns (ProofRecord memory record)
    {
        require(proofRecords[documentNumberHash].exists, "Proof record not found");
        return proofRecords[documentNumberHash];
    }
    
    /**
     * @notice Check if a document number hash has been used
     * @param documentNumberHash The hash of the document number
     * @return True if the document number has been used
     */
    function isDocumentNumberUsed(bytes32 documentNumberHash)
        external
        view
        returns (bool)
    {
        return proofRecords[documentNumberHash].exists;
    }
    
    /**
     * @notice Get all proof hashes for a user
     * @param user The user address
     * @return Array of document number hashes
     */
    function getUserProofs(address user)
        external
        view
        returns (bytes32[] memory)
    {
        return userProofs[user];
    }
    
    /**
     * @notice Decode public values to extract AgeProofOutput
     * @dev This is a simplified decoder - in production, use a proper bincode decoder
     * The public values are bincode-serialized AgeProofOutput struct:
     * - is_valid: bool (1 byte)
     * - meets_age_requirement: bool (1 byte)
     * - document_number_hash: [u8; 32] (32 bytes)
     * - ... (debug fields)
     * 
     * For simplicity, we'll extract the first two bools and the hash
     * @param publicValues The public values bytes
     * @return isValid Whether passport is valid
     * @return meetsAgeRequirement Whether age requirement is met
     */
    function decodePublicValues(bytes calldata publicValues)
        internal
        pure
        returns (bool isValid, bool meetsAgeRequirement)
    {
        // Bincode serialization format:
        // - Length prefix (varint, typically 1-2 bytes)
        // - is_valid: bool (1 byte: 0x00 = false, 0x01 = true)
        // - meets_age_requirement: bool (1 byte)
        // - document_number_hash: [u8; 32] (32 bytes)
        // - ... more fields
        
        require(publicValues.length >= 35, "Invalid public values length");
        
        // Skip length prefix (usually 1-2 bytes)
        // For simplicity, assume it's 1 byte and skip it
        // In production, properly parse the varint
        uint256 offset = 1;
        
        // Read is_valid (bool, 1 byte)
        isValid = publicValues[offset] != 0;
        offset += 1;
        
        // Read meets_age_requirement (bool, 1 byte)
        meetsAgeRequirement = publicValues[offset] != 0;
        
        // Note: document_number_hash is at offset + 1 (bytes 2-33)
        // We don't need to extract it here since it's passed as a parameter
    }
}

